export type DemoItem = {
  title: string;
  game: "ONE_PIECE" | "POKEMON";
  cardType: string;
  condition: string;
  priceHkd: number;
  description: string;
  imageUrl: string;
};

export const DEMO_ONE_PIECE: DemoItem[] = [
  {
    title: "Monkey D. Luffy OP05-119 Alt Art",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 1980,
    description: "英文 Alt Art，角位靚。旺角面交。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP05/OP05-119_EN.webp",
  },
  {
    title: "Monkey D. Luffy OP05-119 PSA10",
    game: "ONE_PIECE",
    cardType: "GRADED",
    condition: "PSA10",
    priceHkd: 880,
    description: "日版 PSA10，連殼交。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP05/OP05-119_EN.webp",
  },
  {
    title: "Trafalgar Law OP01-002 Super Rare",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 220,
    description: "Romance Dawn Law SR。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP01/OP01-002_EN.webp",
  },
  {
    title: "Roronoa Zoro OP01-025 Alt",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "B",
    priceHkd: 340,
    description: "Zoro Alt，右邊微白。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP01/OP01-025_EN.webp",
  },
  {
    title: "Nami OP01-016",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 95,
    description: "Nami 領導卡，近全新。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP01/OP01-016_EN.webp",
  },
  {
    title: "Shanks OP01-120 SEC",
    game: "ONE_PIECE",
    cardType: "GRADED",
    condition: "PSA9",
    priceHkd: 1680,
    description: "紅髮 SEC PSA9。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP01/OP01-120_EN.webp",
  },
  {
    title: "Yamato OP01-121",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 160,
    description: "Yamato SEC Raw。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP01/OP01-121_EN.webp",
  },
  {
    title: "Boa Hancock OP07-051",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 190,
    description: "Hancock SR。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP07/OP07-051_EN.webp",
  },
  {
    title: "Sanji OP07-064 Super Rare",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 140,
    description: "Sanji SR，近全新。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP07/OP07-064_EN.webp",
  },
  {
    title: "Portgas D. Ace OP02-013",
    game: "ONE_PIECE",
    cardType: "RAW",
    condition: "A",
    priceHkd: 280,
    description: "Ace leader，膠膜未撕過。",
    imageUrl: "https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/OP02/OP02-013_EN.webp",
  },
];

export const DEMO_POKEMON: DemoItem[] = [
  {
    title: "Charizard Base Set #4",
    game: "POKEMON",
    cardType: "RAW",
    condition: "B",
    priceHkd: 4200,
    description: "Base Set Charizard，右邊微白。尖沙咀面交。",
    imageUrl: "https://images.pokemontcg.io/base1/4_hires.png",
  },
  {
    title: "Pikachu Base Set #58",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 180,
    description: "經典黃卡，近全新。",
    imageUrl: "https://images.pokemontcg.io/base1/58_hires.png",
  },
  {
    title: "Umbreon VMAX Evolving Skies #95",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 980,
    description: "Evolving Skies Umbreon VMAX。",
    imageUrl: "https://images.pokemontcg.io/swsh7/95_hires.png",
  },
  {
    title: "Umbreon VMAX Alternate Art #215",
    game: "POKEMON",
    cardType: "GRADED",
    condition: "PSA10",
    priceHkd: 6800,
    description: "Moonbreon PSA10，連殼交。",
    imageUrl: "https://images.pokemontcg.io/swsh7/215_hires.png",
  },
  {
    title: "Mew VMAX Fusion Strike #114",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 260,
    description: "Fusion Strike Mew VMAX。",
    imageUrl: "https://images.pokemontcg.io/swsh8/114_hires.png",
  },
  {
    title: "Gengar VMAX Fusion Strike #157",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 720,
    description: "Gengar VMAX Alt，角位尖。",
    imageUrl: "https://images.pokemontcg.io/swsh8/157_hires.png",
  },
  {
    title: "Rayquaza VMAX Evolving Skies #218",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 1580,
    description: "Rainbow Rayquaza VMAX。",
    imageUrl: "https://images.pokemontcg.io/swsh7/218_hires.png",
  },
  {
    title: "Pikachu VMAX Vivid Voltage #44",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 210,
    description: "Vivid Voltage Pikachu VMAX。",
    imageUrl: "https://images.pokemontcg.io/swsh4/44_hires.png",
  },
  {
    title: "Lugia V Silver Tempest #186",
    game: "POKEMON",
    cardType: "GRADED",
    condition: "PSA9",
    priceHkd: 2400,
    description: "Lugia V Alt PSA9。",
    imageUrl: "https://images.pokemontcg.io/swsh12/186_hires.png",
  },
  {
    title: "Mewtwo GX Shining Legends #39",
    game: "POKEMON",
    cardType: "RAW",
    condition: "A",
    priceHkd: 320,
    description: "Shining Legends Mewtwo GX。",
    imageUrl: "https://images.pokemontcg.io/sm35/39_hires.png",
  },
];

export const DEMO_PRODUCTS = [...DEMO_ONE_PIECE, ...DEMO_POKEMON];
